// <auto-generated />
using System;
using BedtimeStoryTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BedtimeStoryTracker.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720084819_AlignSqlServerSchemaStandards")]
    partial class AlignSqlServerSchemaStandards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BedtimeTracking")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Child_Id");

                    b.ToTable("Child", "BedtimeTracking");
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.ReadingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AfterNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("BeforeNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElapsedSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("StoryTitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_ReadingSession_Id");

                    b.HasIndex(new[] { "StoryId" }, "IX_ReadingSession_StoryId");

                    b.ToTable("ReadingSession", "BedtimeTracking", t =>
                        {
                            t.HasCheckConstraint("CK_ReadingSession_CompletedAtUtc", "[CompletedAtUtc] >= [StartedAtUtc]");

                            t.HasCheckConstraint("CK_ReadingSession_ElapsedSeconds", "[ElapsedSeconds] > 0 AND [ElapsedSeconds] <= 86400");
                        });
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.ReadingSessionChildObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AfterCalmness")
                        .HasColumnType("int");

                    b.Property<int>("BeforeCalmness")
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("ChildNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ReadingSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ReadingSessionChildObservation_Id");

                    b.HasIndex(new[] { "ChildId" }, "IX_ReadingSessionChildObservation_ChildId");

                    b.HasIndex(new[] { "ReadingSessionId", "ChildId" }, "UQ_ReadingSessionChildObservation_ReadingSessionId_ChildId")
                        .IsUnique();

                    b.ToTable("ReadingSessionChildObservation", "BedtimeTracking", t =>
                        {
                            t.HasCheckConstraint("CK_ReadingSessionChildObservation_AfterCalmness", "[AfterCalmness] >= 1 AND [AfterCalmness] <= 5");

                            t.HasCheckConstraint("CK_ReadingSessionChildObservation_BeforeCalmness", "[BeforeCalmness] >= 1 AND [BeforeCalmness] <= 5");
                        });
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ReadingMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_Story_Id");

                    b.ToTable("Story", "BedtimeTracking");
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.StoryParagraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id")
                        .HasName("PK_StoryParagraph_Id");

                    b.HasIndex(new[] { "StoryId", "Sequence" }, "UQ_StoryParagraph_StoryId_Sequence")
                        .IsUnique();

                    b.ToTable("StoryParagraph", "BedtimeTracking");
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.ReadingSession", b =>
                {
                    b.HasOne("BedtimeStoryTracker.Api.Entities.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReadingSession_Story");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.ReadingSessionChildObservation", b =>
                {
                    b.HasOne("BedtimeStoryTracker.Api.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReadingSessionChildObservation_Child");

                    b.HasOne("BedtimeStoryTracker.Api.Entities.ReadingSession", "ReadingSession")
                        .WithMany("ChildObservations")
                        .HasForeignKey("ReadingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReadingSessionChildObservation_ReadingSession");

                    b.Navigation("Child");

                    b.Navigation("ReadingSession");
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.StoryParagraph", b =>
                {
                    b.HasOne("BedtimeStoryTracker.Api.Entities.Story", "Story")
                        .WithMany("Paragraphs")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StoryParagraph_Story");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.ReadingSession", b =>
                {
                    b.Navigation("ChildObservations");
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.Story", b =>
                {
                    b.Navigation("Paragraphs");
                });
#pragma warning restore 612, 618
        }
    }
}
