// <auto-generated />
using System;
using BedtimeStoryTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BedtimeStoryTracker.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260719202526_AddReadingSessions")]
    partial class AddReadingSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.Child", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Children", (string)null);
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.ReadingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AfterNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("BeforeNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ElapsedSeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoryTitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("ReadingSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReadingSessions_CompletedAfterStarted", "[CompletedAtUtc] >= [StartedAtUtc]");

                            t.HasCheckConstraint("CK_ReadingSessions_ElapsedSeconds", "[ElapsedSeconds] > 0 AND [ElapsedSeconds] <= 86400");
                        });
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.ReadingSessionChildObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AfterCalmness")
                        .HasColumnType("int");

                    b.Property<int>("BeforeCalmness")
                        .HasColumnType("int");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChildNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ReadingSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ReadingSessionId", "ChildId")
                        .IsUnique();

                    b.ToTable("ReadingSessionChildObservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReadingSessionChildObservations_AfterCalmness", "[AfterCalmness] >= 1 AND [AfterCalmness] <= 5");

                            t.HasCheckConstraint("CK_ReadingSessionChildObservations_BeforeCalmness", "[BeforeCalmness] >= 1 AND [BeforeCalmness] <= 5");
                        });
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.Story", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ReadingMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Stories", (string)null);
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.StoryParagraph", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("StoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("StoryId", "Sequence")
                        .IsUnique();

                    b.ToTable("StoryParagraphs", (string)null);
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.ReadingSession", b =>
                {
                    b.HasOne("BedtimeStoryTracker.Api.Entities.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.ReadingSessionChildObservation", b =>
                {
                    b.HasOne("BedtimeStoryTracker.Api.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BedtimeStoryTracker.Api.Entities.ReadingSession", "ReadingSession")
                        .WithMany("ChildObservations")
                        .HasForeignKey("ReadingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("ReadingSession");
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.StoryParagraph", b =>
                {
                    b.HasOne("BedtimeStoryTracker.Api.Entities.Story", "Story")
                        .WithMany("Paragraphs")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.ReadingSession", b =>
                {
                    b.Navigation("ChildObservations");
                });

            modelBuilder.Entity("BedtimeStoryTracker.Api.Entities.Story", b =>
                {
                    b.Navigation("Paragraphs");
                });
#pragma warning restore 612, 618
        }
    }
}
